"""The ai-toolkit backend. FLUX.2, Klein and Krea 2 as one config-driven class.

v1 has two classes here, one subclassing the other, differing mostly in
which strings they put in a YAML file (doc 01). They collapse into this,
with the per-model differences in ``models.py`` where they can be read.

**Quirks carried forward from v1, each of which cost somebody an evening.**
They are not obvious from ai-toolkit's docs and they are not guessable:

* **``lr`` is the key that is read, not ``learning_rate``.** The train
  config derives ``unet_lr`` from ``lr`` and falls back to a near-zero
  1e-6 when it is missing, so a run configured only with
  ``learning_rate`` trains at a rate that looks like nothing happening.
  Both are written.
* **Caching is a dataset-level setting**, not a train-level one:
  ``cache_latents_to_disk`` and ``cache_text_embeddings`` live in the
  dataset block. Setting them under ``train`` silently does nothing, and
  the VAE and text encoder then stay resident and take the VRAM the
  transformer needed.
* **``skip_first_sample`` is a train key.** The ``sample_at_first`` key in
  the sample block is ignored by current upstream, and a baseline sample
  on a 12B model is slow and can produce NaN on an untrained network.
* **The arch strings are ``flux2_klein_4b`` / ``flux2_klein_9b``.** v1
  emits ``flux2_klein``, which does not exist.

New here: ``mask_path`` is threaded from the dataset into the generated
config, which is the one line the whole masking feature exists to produce
(doc 04).
"""

from __future__ import annotations

import os
import re
import threading
from pathlib import Path
from typing import Any

from .. import paths
from ..events import Emitter, Log, LossPoint, Progress, no_op, safe
from . import BackendError, BackendProgress, register
from .models import Model, UnknownModel
from .models import find as find_model
from .models import get as get_model
from .process import ProcessRunner, python_executable
from .spec import RunSpec, run_name as spec_run_name

#: ai-toolkit's entry point, relative to its checkout.
RUNNER = "run.py"

#: How many times each image is seen per epoch. v1's constant, kept: the
#: datasets here are small enough that one pass is not a meaningful epoch.
DEFAULT_REPEATS = 10

#: Only when neither a save interval nor a sample interval was given.
#: Checkpoints are hundreds of megabytes each, so this is deliberately not
#: small.
DEFAULT_SAVE_EVERY = 500

#: Written into every generated config, so nobody hand-edits an artifact.
HEADER = (
    "# Generated by FluxKrea Trainer from a RunSpec. Do not hand-edit:\n"
    "# this file is rewritten every time the job is submitted.\n"
    "# Change the spec, not the artifact.\n"
)


# --------------------------------------------------------------------------
# output parsing
# --------------------------------------------------------------------------

#: ai-toolkit reports progress in several shapes depending on where it is:
#: an explicit step line, a tqdm bar, or a percentage with counts.
STEP_PATTERNS = (
    re.compile(r"[Ss]tep[:\s]+(\d+)\s*/\s*(\d+)"),
    re.compile(r"\|\s*(\d+)\s*/\s*(\d+)\s*\["),
    re.compile(r"\d+%\|?\s*(\d+)\s*/\s*(\d+)"),
)

#: Scientific notation included - ai-toolkit prints ``loss: 3.698e-01``.
LOSS_PATTERN = re.compile(r"[Ll]oss[:\s=]+([0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?)")

#: Lines worth raising to warning, so a failing run is visible in a tail.
TROUBLE = ("Traceback", "CUDA out of memory", "RuntimeError", "torch.OutOfMemoryError")


class OutputParser:
    """Turns ai-toolkit's stdout into ``Progress`` and ``LossPoint`` events.

    Separate from the backend so it can be tested against captured output
    without launching anything - which matters, because every one of these
    patterns is a guess about somebody else's formatting.
    """

    def __init__(self, emit: Emitter, total: int = 0) -> None:
        self.emit = safe(emit)
        self.step = 0
        self.total = total
        self.loss: float | None = None

    def __call__(self, line: str) -> bool:
        """Handle one line. Returns True if the raw line need not be logged."""
        redrawn_bar = False

        for index, pattern in enumerate(STEP_PATTERNS):
            match = pattern.search(line)
            if match:
                step, total = int(match.group(1)), int(match.group(2))
                # A sampling or caching bar counts to its own total; only
                # accept one that matches the run we are actually tracking.
                if self.total and total != self.total:
                    break
                self.step, self.total = step, total or self.total
                self.emit(Progress(step=self.step, total=self.total, message="Training"))
                # Patterns 1 and 2 are tqdm redrawing itself. Suppressing
                # those keeps a log tail readable; an explicit "step: x/y"
                # line is worth keeping.
                redrawn_bar = index > 0
                break

        loss = LOSS_PATTERN.search(line)
        if loss:
            try:
                value = float(loss.group(1))
            except ValueError:
                value = None
            if value is not None:
                self.loss = value
                self.emit(LossPoint(step=self.step, value=value))

        if any(marker in line for marker in TROUBLE):
            self.emit(Log(line=line, level="error"))
            return True

        return redrawn_bar

    def progress(self) -> BackendProgress:
        return BackendProgress(step=self.step, total=self.total, message="Training")


# --------------------------------------------------------------------------
# the backend
# --------------------------------------------------------------------------


class AIToolkitBackend:
    """FLUX.2, Klein and Krea 2, through ai-toolkit's ``sd_trainer``."""

    name = "aitoolkit"

    def __init__(
        self,
        toolkit_path: str | os.PathLike[str] | None = None,
        *,
        python_exe: str = "",
        output_root: str | os.PathLike[str] | None = None,
    ) -> None:
        self.toolkit_path = paths.expand(toolkit_path) if toolkit_path else None
        self.python_exe = python_exe
        self.output_root = paths.expand(output_root) if output_root else None
        self._runner: ProcessRunner | None = None
        self._parser: OutputParser | None = None
        self._lock = threading.Lock()

    @classmethod
    def from_config(cls, config: Any) -> AIToolkitBackend:
        """Build from the app config, which is where the paths live."""
        return cls(
            config.backends.aitoolkit_path,
            python_exe=config.backends.python_exe,
            output_root=config.backends.output_root,
        )

    # -- dispatch ---------------------------------------------------------

    def supports(self, model_id: str) -> bool:
        return find_model(model_id) is not None

    def models(self) -> list[dict[str, object]]:
        from .models import listing

        return listing()

    def available(self) -> bool:
        """Whether this node could actually run a job right now."""
        return self.runner_script().is_file() if self.toolkit_path else False

    def runner_script(self) -> Path:
        if self.toolkit_path is None:
            raise BackendError(
                "backends.aitoolkit_path is not set, so there is no ai-toolkit to run. "
                "Point it at the checkout on this node."
            )
        return self.toolkit_path / RUNNER

    # -- config generation ------------------------------------------------

    def generate_config(self, run: RunSpec) -> Path:
        """Render the spec into an ai-toolkit YAML config.

        A generated artifact, written from the spec, never the source of
        truth (doc 02). It is rewritten on every submission.
        """
        import yaml

        model = get_model(run.model)
        payload = self.build(run, model)

        target = self.config_path(run)
        body = HEADER + yaml.dump(payload, default_flow_style=False, sort_keys=False)
        try:
            paths.ensure_dir(target.parent)
            target.write_text(body, encoding="utf-8")
        except OSError as exc:
            raise BackendError(_write_failure(target, exc)) from exc
        return target

    def output_folder(self, run: RunSpec) -> Path:
        """Where this run writes: checkpoints, samples and its own config.

        The same folder ai-toolkit resolves as ``save_root``, which is what
        makes the sample strip and the checkpoint list find anything.
        """
        if run.output:
            return paths.expand(run.output)
        root = self.output_root or paths.runs_dir()
        return paths.expand(root) / self.run_name(run)

    def config_path(self, run: RunSpec) -> Path:
        """Beside the run's own output, not in a folder of its own.

        The config describes exactly one run and is rewritten on every
        submission, so it belongs with the checkpoints and samples it
        produced. It used to derive its own folder, which could - and did -
        differ from the one the run actually wrote into.
        """
        folder = self.output_folder(run)
        return folder / f"{folder.name}.yaml"

    def run_name(self, run: RunSpec) -> str:
        return spec_run_name(run)

    def build(self, run: RunSpec, model: Model | None = None) -> dict[str, Any]:
        """The config, as a dict. Split out so a test can read it."""
        model = model or get_model(run.model)
        output = self.output_folder(run)

        # ai-toolkit appends the job name to `training_folder` itself:
        #
        #   BaseTrainProcess.py:45
        #   self.save_root = os.path.join(self.training_folder, self.name)
        #
        # so handing it the run's own folder produced
        # `runs/<name>/<name>/`, with checkpoints and samples one level
        # below everything that looks for them. Give it the parent and let
        # it build the folder, so `save_root` *is* the run's output folder.
        name = output.name

        return {
            "job": "extension",
            "config": {
                "name": name,
                "process": [
                    {
                        "type": "sd_trainer",
                        "training_folder": output.parent.as_posix(),
                        "device": f"cuda:{run.device}",
                        "model": self._model_block(run, model),
                        "network": self._network_block(run, model),
                        "save": self._save_block(run),
                        "datasets": [self._dataset_block(run)],
                        "train": self._train_block(run, model),
                        **self._sample_block(run, model),
                    }
                ],
            },
        }

    def _model_block(self, run: RunSpec, model: Model) -> dict[str, Any]:
        block: dict[str, Any] = {
            "name_or_path": _posix(run.extra.get("model_path") or run.model),
            "is_flux": model.is_flux,
            "quantize": bool(run.extra.get("quantize", True)),
            "quantize_te": bool(run.extra.get("quantize_te", True)),
            "low_vram": bool(run.extra.get("low_vram", model.low_vram)),
            # Layer offloading is slow enough to be the wrong trade even at
            # 30%, which v1 discovered and wrote down. Off unless asked for.
            "layer_offloading": bool(run.extra.get("layer_offloading", False)),
        }
        if model.arch:
            block["arch"] = model.arch
        if vae := run.extra.get("vae_path"):
            # Krea 2 resolves its own VAE; setting one here fights the arch.
            if model.id == "krea2":
                raise BackendError("krea2 resolves its own VAE - do not set vae_path")
            block["vae_path"] = _posix(vae)
        return block

    def _network_block(self, run: RunSpec, model: Model) -> dict[str, Any]:
        dim = run.network_dim or model.network_dim
        alpha = run.network_alpha or model.network_alpha or dim
        return {"type": "lora", "linear": dim, "linear_alpha": alpha}

    def _save_block(self, run: RunSpec) -> dict[str, Any]:
        return {
            "dtype": str(run.extra.get("save_dtype", "bf16")),
            # Checkpoints default to the sample interval: the two are the
            # points you look at a run, and a checkpoint you cannot see a
            # sample for is hard to judge. Explicit wins over both.
            "save_every": run.save_every or run.sample_every or DEFAULT_SAVE_EVERY,
            "max_step_saves_to_keep": int(run.extra.get("max_saves", 3)),
        }

    def _dataset_block(self, run: RunSpec) -> dict[str, Any]:
        """The dataset block - and the one line masking exists to produce."""
        block: dict[str, Any] = {
            "folder_path": _posix(run.dataset),
            "caption_ext": "txt",
            "num_repeats": int(run.extra.get("num_repeats", DEFAULT_REPEATS)),
            # Dataset-level, not train-level. See the module docstring.
            "cache_latents_to_disk": bool(run.extra.get("cache_latents", True)),
            "cache_text_embeddings": bool(run.extra.get("cache_text_embeddings", True)),
        }
        if run.resolution:
            block["resolution"] = run.resolution

        if run.mask_path:
            # Masks are matched by basename from this folder, and an image
            # with no match trains unmasked without warning - which is why
            # `fk dataset validate --require-masks` exists.
            block["mask_path"] = _posix(run.mask_path)
            block["mask_min_value"] = run.mask_min_value
        return block

    def _train_block(self, run: RunSpec, model: Model) -> dict[str, Any]:
        lr = run.learning_rate or 0.0001
        return {
            "batch_size": run.batch_size or 1,
            "steps": run.steps or 1000,
            "gradient_accumulation_steps": int(run.extra.get("gradient_accumulation_steps", 1)),
            "train_unet": True,
            "train_text_encoder": False,
            # `lr` is the key that is read; `learning_rate` alone trains at
            # a near-zero default. Both, deliberately.
            "lr": lr,
            "learning_rate": lr,
            "lr_scheduler": str(run.extra.get("lr_scheduler", "constant")),
            "optimizer": str(run.extra.get("optimizer", "adamw8bit")),
            "gradient_checkpointing": True,
            "noise_scheduler": "flowmatch",
            "max_denoising_steps": 1000,
            "dtype": "bf16",
            "max_grad_norm": 1.0,
            # A baseline sample on an untrained network is slow and can NaN.
            "skip_first_sample": bool(run.extra.get("skip_first_sample", True)),
        }

    def _sample_block(self, run: RunSpec, model: Model) -> dict[str, Any]:
        prompts = [p for p in (run.extra.get("sample_prompts") or []) if str(p).strip()]
        if not run.sample_every or not prompts:
            return {}

        guidance = float(run.extra.get("guidance_scale", model.guidance_scale))
        steps = int(run.extra.get("sample_steps", model.sample_steps))
        width = int(run.extra.get("sample_width", 512))
        height = int(run.extra.get("sample_height", 512))
        seed = run.seed if run.seed is not None else 42

        return {
            "sample": {
                "sampler": "flowmatch",
                "sample_every": run.sample_every,
                "width": width,
                "height": height,
                "samples": [
                    {
                        "prompt": str(prompt),
                        "neg": "",
                        "seed": seed,
                        "walk_seed": True,
                        "guidance_scale": guidance,
                        "sample_steps": steps,
                    }
                    for prompt in prompts
                ],
                "neg": "",
                "seed": seed,
                "walk_seed": True,
                "guidance_scale": guidance,
                "sample_steps": steps,
            }
        }

    # -- running ----------------------------------------------------------

    def start(
        self,
        config_path: Path,
        emit: Emitter = no_op,
        cancel: threading.Event | None = None,
        *,
        total_steps: int = 0,
    ) -> None:
        """Launch training and stream it. Blocking; raises on failure."""
        emit = safe(emit)
        script = self.runner_script()
        if not script.is_file():
            raise BackendError(f"ai-toolkit not found at {script}")
        if not Path(config_path).is_file():
            raise BackendError(f"config not found: {config_path}")

        command = [
            python_executable(self.python_exe),
            str(script),
            str(config_path),
        ]
        parser = OutputParser(emit, total=total_steps)
        # cwd is the toolkit checkout: run.py does sys.path.insert(0, cwd)
        # and load_dotenv() from there, so its .env and its packages are
        # only found when it is launched from its own directory.
        runner = ProcessRunner(command, cwd=self.toolkit_path)

        with self._lock:
            self._runner = runner
            self._parser = parser

        emit(Log(line=f"Starting ai-toolkit: {config_path.name}"))
        code = runner.run(emit, cancel, on_line=parser)

        with self._lock:
            self._runner = None

        if cancel is not None and cancel.is_set():
            emit(Log(line="Training stopped", level="warning"))
            return
        if code != 0:
            raise BackendError(f"ai-toolkit exited with code {code}")

    def stop(self) -> None:
        with self._lock:
            runner = self._runner
        if runner is not None:
            runner.stop()

    def is_running(self) -> bool:
        with self._lock:
            runner = self._runner
        return runner is not None and runner.is_running()

    def progress(self) -> BackendProgress:
        with self._lock:
            parser = self._parser
        return parser.progress() if parser else BackendProgress()


def _posix(value: Any) -> str:
    """Paths go into the config as forward slashes, on both platforms.

    The same config is readable on the Windows desk and the Linux node, and
    a YAML-quoted backslash is a escape waiting to happen.
    """
    return paths.expand(str(value)).as_posix() if _looks_like_path(value) else str(value)


def _looks_like_path(value: Any) -> bool:
    text = str(value)
    return "/" in text or "\\" in text


#: Registered at import time, so ``supported_by`` finds it.
BACKEND = register(AIToolkitBackend())

#: Windows refuses paths past this unless long paths are enabled, and
#: reports it as a plain "no such file or directory" - which sends you
#: looking for a missing file rather than a name that is too long.
WINDOWS_MAX_PATH = 260


def _write_failure(target: Path, exc: OSError) -> str:
    """Turn a failed config write into something that names the cause.

    A run whose name came from a full dataset path produced a 264-character
    config path here, and the only symptom was FileNotFoundError on a file
    the code had just tried to create.
    """
    length = len(str(target))
    if os.name == "nt" and length > WINDOWS_MAX_PATH:
        return (
            f"cannot write the run config: the path is {length} characters, past "
            f"Windows' {WINDOWS_MAX_PATH}-character limit.\n  {target}\n"
            "Give the run a shorter name, point backends.output_root at a "
            "shallower folder, or enable long paths on this node."
        )
    return f"cannot write the run config to {target}: {exc}"


__all__ = ["BACKEND", "AIToolkitBackend", "OutputParser", "UnknownModel"]
